#
# Create the required serviceaccount and clusterrolebindings for the authentication
# Make sure specify the service account name match with the environment variable - `PROW_BUILD_CLUSTER_SERVICE_ACCOUNT_NAME` for the job
# Later the automated job is creating token with this service account as the subject
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccount-cluster-admin   # service account name should match with env `PROW_BUILD_CLUSTER_SERVICE_ACCOUNT_NAME`
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serviceaccount-cluster-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: serviceaccount-cluster-admin
  namespace: default