plank:
  job_url_prefix_config:
    '*': https://prow.andytauber.info/view/
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 5m
  default_decoration_config_entries:
  - config:
      timeout: 2h
      grace_period: 15m
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20220810-a8a8778c45"
        initupload: "gcr.io/k8s-prow/initupload:v20220810-a8a8778c45"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20220810-a8a8778c45"
        sidecar: "gcr.io/k8s-prow/sidecar:v20220810-a8a8778c45"
      gcs_configuration:
        bucket: sandbox-gcs-publisher
        path_strategy: "explicit"
      gcs_credentials_secret: "gcs-credentials"
      resources:
        clonerefs:
          requests:
            cpu: 100m
        initupload:
          requests:
            cpu: 100m
        place_entrypoint:
          requests:
            cpu: 100m
        sidecar:
          requests:
            cpu: 100m
  - cluster: tkg-es-infra-prow-build
    config:
      gcs_credentials_secret: "" # Use workload identity
      gcs_configuration:
        bucket: "tkg-es-openbtr-prow"
      default_service_account_name: "prowjob-default-sa"

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m

deck:
  spyglass:
    size_limit: 100000000 # 100MB
    gcs_browser_prefix: https://console.cloud.google.com/storage/browser/
    lenses:
    - lens:
        name: metadata
      required_files:
      - ^(?:started|finished)\.json$
      optional_files:
      - ^(?:podinfo|prowjob)\.json$
    - lens:
        name: buildlog
        config:
          highlight_regexes:
          - timed out
          - "ERROR:"
          - (FAIL|Failure \[)\b
          - panic\b
          - ^E\d{4} \d\d:\d\d:\d\d\.\d\d\d]
          # This highlights the start of bazel tests/runs to skip go importing noise.
          - "^INFO: Analyzed \\d+ targets"
      required_files:
        - ^.*build-log\.txt$
    - lens:
        name: junit
      required_files:
        - ^artifacts(/.*/|/)junit.*\.xml$ # https://regex101.com/r/vCSegS/1
    - lens:
        name: coverage
      required_files:
        - ^artifacts/filtered\.cov$
      optional_files:
        - ^artifacts/filtered\.html$
    - lens:
        name: podinfo
      required_files:
        - ^podinfo\.json$
    - lens:
        name: links
      required_files:
        - artifacts/.*\.link\.txt
  tide_update_period: 1s


prowjob_namespace: prow
pod_namespace: test-pods
log_level: debug

tide:
  sync_period: 2m
  queries:
  - orgs:
    - AndyTauber
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/contains-merge-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase

  pr_status_base_urls:
    '*': https://prow.andytauber.info/pr
  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge
  priority:
  - labels: [ "kind/flake", "priority/critical-urgent" ]
  - labels: [ "kind/failing-test", "priority/critical-urgent" ]
  - labels: [ "kind/bug", "priority/critical-urgent" ]

push_gateway:
# remove the pushgateway endpoint for now to reduce logging spam
# endpoint: pushgateway
  endpoint:
  serve_metrics: true

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit

presets:
# docker-in-docker preset
- labels:
    preset-dind-enabled: "true"
  env:
  - name: DOCKER_IN_DOCKER_ENABLED
    value: "true"
  volumes:
  - name: docker-graph
    emptyDir: {}
  - name: docker-root
    emptyDir: {}
  volumeMounts:
  - name: docker-graph
    mountPath: /docker-graph
  - name: docker-root
    mountPath: /var/lib/docker
# kind volume volumeMounts
- labels:
    preset-kind-volume-mounts: "true"
  volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
# GCP project environment variables
- labels:
    preset-gc-compute-envs: "true"
  env:
    - name: CLOUDSDK_COMPUTE_REGION
      value: "us-west1"
- labels:
    preset-gc-project-env: "true"
  env:
    - name: CLOUDSDK_CORE_PROJECT
      value: "prow-open-btr"
# gcp integration tests
# https://cloud.google.com/compute/docs/tutorials/service-account-ssh
# https://cloud.google.com/compute/docs/oslogin/set-up-oslogin
- labels:
    preset-sa-gcp-prow-integration: "true" # Service account with "Compute Admin" and "Compute OS Admin Login" roles
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/credentials/sa-gcp-prow-integration/service-account.json
  volumes:
    - name: sa-gcp-prow-integration
      secret:
        secretName: sa-gcp-prow-integration
  volumeMounts:
    - name: sa-gcp-prow-integration
      mountPath: /etc/credentials/sa-gcp-prow-integration
      readOnly: true
# gke integration tests
- labels:
    preset-sa-gke-prow-integration: "true"
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/credentials/sa-gke-prow-integration/service-account.json
  volumes:
    - name: sa-gke-prow-integration
      secret:
        secretName: sa-gke-prow-integration
  volumeMounts:
    - name: sa-gke-prow-integration
      mountPath: /etc/credentials/sa-gke-prow-integration
      readOnly: true
