postsubmits:
  GITHUB_ORG/GITHUB_REPO1:
  - name: test-postsubmit-andy-infra
    cluster: prow-service-trusted
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
