# ProwJobs defined in this file specify `cluster: andy-infra in order to run in Prow's service cluster.
### comment to initiate config-updater deploy ###
postsubmits:
  AndyTauber/andy-infra:
  - name: post-andy-infra-deploy-prow-ver5
    cluster: prow-service-trusted
    run_if_changed: '^config/prow/cluster/'
    decorate: true
    branches:
    - main
    spec:
      containers:
      - image: public.ecr.aws/t0q8k6g2/vagator/test-image:v20221003-6f693ab
        command:
        - /usr/local/bin/run.sh
        args:
        - AndyTauber
        - andy-infra
        - cd ./config && make deploy
        env:
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config:/etc/kubeconfig/config"
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
