---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secretmanager-cred
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-service-secretstore
    kind: ClusterSecretStore
  target:
    name: secretmanager-cred
    creationPolicy: Owner
  data:
  - secretKey: "service-account.json"
    remoteRef:
      key: secretmanager-cred
