
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: prow-build-secretstore
  namespace: default
spec:
  provider:
    gcpsm:
      projectID: prow-open-btr
      auth:
        workloadIdentity:
          # name of the cluster region
          clusterLocation: us-west1-a
          # name of the GKE cluster
          clusterName: prow-build
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          # clusterProjectID: my-cluster-project
          # reference the sa from above
          serviceAccountRef:
            name: prow-build-secrets-sa
            namespace: default
