---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcs-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: gcs-credentials
    creationPolicy: Owner
  data:
  - secretKey: "service-account.json"
    remoteRef:
      key: gcs-publisher
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sa-gcp-prow-integration
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: sa-gcp-prow-integration
    creationPolicy: Owner
  data:
  - secretKey: service-account.json
    remoteRef:
      key: sa-gcp-prow-integration
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sa-gke-prow-integration
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: sa-gke-prow-integration
    creationPolicy: Owner
  data:
  - secretKey: service-account.json
    remoteRef:
      key: sa-gke-prow-integration
