---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secretmanager-cred
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: secretmanager-cred
    creationPolicy: Owner
  data:
  - secretKey: "service-account.json"
    remoteRef:
      key: secretmanager-cred
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: kubeconfig-default
    creationPolicy: Owner
  data:
  - secretKey: config
    remoteRef:
      key: kubeconfig-default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-prow-gke-build
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: kubeconfig-prow-gke-build
    creationPolicy: Owner
  data:
  - secretKey: config
    remoteRef:
      key: kubeconfig-prow-gke-build
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfig-prow-service-trusted
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: prow-build-secretstore
    kind: ClusterSecretStore
  target:
    name: kubeconfig-prow-service-trusted
    creationPolicy: Owner
  data:
  - secretKey: config
    remoteRef:
      key: kubeconfig-prow-service-trusted
