# sample jobs for info
presubmits:
  AndyTauber/andy-prow:
  - name: andy-prow-presubmit-print
    cluster: prow-gke-build
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
