# sample jobs for info
postsubmits:
  AndyTauber/andy-infra:
  - name: andy-infra-postsubmit-print
    cluster: prow-service-trusted
    decorate: true
    always_run: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
