periodics:
- interval: 1m
  name: ci-kubernetes-unit
  cluster: prow-gke-build
  annotations:
    fork-per-release: "true"
  decorate: true
  extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    # unit tests have no business requiring root or doing privileged operations
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220804-4fa19ea91a-master
        command:
          - make
          - test
        # TODO: direct copy from pull-kubernetes-bazel-test, tune these
        resources:
          limits:
            cpu: 8
            memory: "64Gi"
          requests:
            cpu: 4
            memory: "36Gi"