periodics:
- interval: 1h
  name: ci-kubernetes-unit
  cluster: tkg-es-infra-prow-build
  annotations:
    fork-per-release: "true"
  decorate: true
  extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    # unit tests have no business requiring root or doing privileged operations
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220804-4fa19ea91a-master
        command:
          - make
          - test
        # TODO: direct copy from pull-kubernetes-bazel-test, tune these
        resources:
          limits:
            cpu: 4
            memory: "36Gi"
          requests:
            cpu: 4
            memory: "36Gi"
- interval: 1h
  name: ci-kubernetes-kind-e2e-parallel
  cluster: tkg-es-infra-prow-build
  annotations:
    description: Uses kubetest to run e2e tests against a latest kubernetes master cluster created with sigs.k8s.io/kind
    fork-per-release: "true"
    fork-per-release-periodic-interval: 1h 2h 6h 24h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 60m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20220804-9dd62ce78a-master
      command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: FOCUS
        value: "."
      # TODO(bentheelder): reduce the skip list further
      - name: SKIP
        value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Network.should.set.TCP.CLOSE_WAIT.timeout|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing|should.provide.basic.identity
      - name: PARALLEL
        value: "true"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        limits:
          memory: 9Gi
          cpu: 7
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: 9Gi
          cpu: 7
- interval: 1m
  name: ci-kubernetes-verify-master
  cluster: tkg-es-infra-prow-build
  labels:
    preset-sa-gcp-prow-integration: "true"
    preset-dind-enabled: "true"
  annotations:
    fork-per-release: "true"
    fork-per-release-periodic-interval: 2h 2h 6h 24h
    description: "Ends up running: make verify"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220804-4fa19ea91a-master
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./hack/jenkins/verify-dockerized.sh
      env:
      - name: EXCLUDE_READONLY_PACKAGE
        value: "y"
      - name: KUBE_VERIFY_GIT_BRANCH
        value: master
      - name: REPO_DIR
        value: /workspace/k8s.io/kubernetes
      # Consider removing after https://github.com/golang/go/issues/49035 is solved
      # See https://github.com/kubernetes/kubernetes/pull/108618
      - name: TYPECHECK_SERIAL
        value: "true"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 6
          memory: 24Gi
        requests:
          cpu: 6
          memory: 24Gi