---
#gitHubLogin: "AndyTauber-ci-robot"
gitHubToken: "/etc/github-token/oauth"
gitName: "AndyTauber Prow Robot"
gitEmail: "atauber@vmware.com"
#onCallAddress: "https://storage.googleapis.com/kubernetes-jenkins/oncall.json"
selfAssign: true # Commenting `/cc`, so that autobump PR is not assigned to anyone
skipPullRequest: false
gitHubOrg: "AndyTauber"
gitHubRepo: "andy-infra"
remoteName: "andy-infra"
upstreamURLBase: "https://raw.githubusercontent.com/AndyTauber/andy-infra/main"
includedConfigPaths:
  - "."
excludedConfigPaths:
  - ".ko.yaml" # Contains gcr.io/k8s-prow/git, which is not pushed by prow
targetVersion: "latest"
prefixes:
  - name: "Prow"
    prefix: "gcr.io/k8s-prow/"
    refConfigFile: "config/prow/cluster/deck.yaml"
    repo: "https://github.com/AndyTauber/andy-infra"
    summarise: true
    consistentImages: true
#  - name: "Boskos"
#    prefix: "gcr.io/k8s-staging-boskos/"
#    refConfigFile: "config/prow/cluster/build/boskos.yaml"
#    repo: "https://github.com/kubernetes-sigs/boskos"
#    summarise: false
#    consistentImages: true
